name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Run rule validation
      run: |
        python scripts/validate_rules.py --path rules
    - name: Merge rule sets
      run: |
        python scripts/merge_rules.py --path rules --output output
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: my-artifact
        path: output/*json
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "my-artifact"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
    
